database_type: SQLite
mysql:
  host: localhost
  port: 3306
  database: dbName
  username: dbUser
  password: dbPass
modules:
  tokens: true
  gems: true
  ranks: true
  multipliers: true
  enchants: true
  autosell: true
  autominer: true
  pickaxe_levels: true
  gangs: true
  friends: true
supported-pickaxes:
  - DIAMOND_PICKAXE
main-command-aliases:
  - upc
  - prisoncore
  - ultraprison
  - prison
  - ultraprisoncore